---
# tasks file for workstation

- name: Add repositorys from PPA and install its signing key
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "ppa:lutris-team/lutris"
    - "ppa:daniruiz/flat-remix"
    - "ppa:phoerious/keepassxc"
    - "ppa:libreoffice/ppa"
    - "ppa:teejee2008/ppa"
    - "ppa:remmina-ppa-team/remmina-next"

- name: Update apt-get repo and cache
   apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
- name: Install useful packages
  apt:
    name:
    - synaptic
    - elisa
    - drawing
    - krdc
    - filezilla
    - network-manager-strongswan 
    - strongswan 
    - libcharon-extra-plugins
    - network-manager-openvpn
    - virt-manager 
    - ssh-askpass-gnome
    - gir1.2-spiceclientgtk-3.0
    - traceroute 
    - net-tools 
    - nmap
    - gnome-multi-writer 
    - gnome-disk-utility
    - lutris
    - flat-remix
    - keepassxc
    - libreoffice
    - vlc
    - thunderbird
    - okular
    - timeshift
    - remmina
    - remmina-plugin-rdp
    state: latest

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes
